export const INITIAL_EMPLOYERS = [
  { name: "SPIN", category: "Education & Educational Partners", website: "https://spininc.org/careers/" },
  { name: "Children’s Village", category: "Education & Educational Partners", website: "https://www.childrensvillagephila.org/careers/" },
  { name: "Acelero", category: "Education & Educational Partners", website: "https://acelero.wd1.myworkdayjobs.com/AceleroLearningCareers" },
  { name: "School District of Philadelphia", category: "Education & Educational Partners", website: "https://jobs.philasd.org/" },
  { name: "Temple University", category: "Education & Educational Partners", website: "https://careers.temple.edu/" },
  { name: "University of Pennsylvania (UPenn)", category: "Education & Educational Partners", website: "https://wd1.myworkdaysite.com/recruiting/upenn/careers-at-penn" },
  { name: "Devereux", category: "Education & Educational Partners", website: "https://jobs.devereux.org/" },
  { name: "Bank of America", category: "Financial & Banking Partners", website: "https://careers.bankofamerica.com/" },
  { name: "Santander", category: "Financial & Banking Partners", website: "https://jobs.santanderbank.com/" },
  { name: "M&T Bank", category: "Financial & Banking Partners", website: "https://www.mtb.com/careers" },
  { name: "Asian Bank", category: "Financial & Banking Partners", website: "https://www.theasianbank.com/about-us/#Career-Opportunities" },
  { name: "Lincoln Financial", category: "Financial & Banking Partners", website: "https://jobs.lincolnfinancial.com/" },
  { name: "Vanguard", category: "Financial & Banking Partners", website: "https://www.vanguardjobs.com/" },
  { name: "TD Bank", category: "Financial & Banking Partners", website: "https://td.wd3.myworkdayjobs.com/TD_Bank_Careers" },
  { name: "PNC", category: "Financial & Banking Partners", website: "https://pnc.wd5.myworkdayjobs.com/External" },
  { name: "Bala Engineers", category: "Engineering & Industry Partners", website: "https://www.bala.com/careers" },
  { name: "Urban Engineers", category: "Engineering & Industry Partners", website: "https://www.paycomonline.net/v4/ats/web.php/jobs?clientkey=88F7766172430555A06D80ADC5873950" },
  { name: "DVM Power", category: "Engineering & Industry Partners", website: "https://dvmpower.com/careers" },
  { name: "Trane Technologies", category: "Engineering & Industry Partners", website: "https://tranetechnologies.wd12.myworkdayjobs.com/Trane_Technologies_Careers" },
  { name: "KAKS & Company", category: "Engineering & Industry Partners", website: "https://kakscompany.com/careers" },
  { name: "IFM", category: "Engineering & Industry Partners", website: "https://jobs.ifm.com/" },
  { name: "Johnson & Johnson", category: "Engineering & Industry Partners", website: "https://jj.wd5.myworkdayjobs.com/JJ" },
  { name: "City of Philadelphia", category: "Governmental Partners", website: "https://www.governmentjobs.com/careers/phila" },
  { name: "Montgomery County", category: "Governmental Partners", website: "https://www.governmentjobs.com/careers/montcopa" },
  { name: "Center City District", category: "Governmental Partners", website: "https://centercityphila.org/who-we-are/careers/" },
  { name: "SEPTA", category: "Governmental Partners", website: "https://jobs.septa.org/" },
  { name: "PHMC", category: "Nonprofit & Community Organizations", website: "https://www.phmc.org/site/careers" },
  { name: "JEVS", category: "Nonprofit & Community Organizations", website: "https://www.hirebridge.com/v3/jobs/list.aspx?cid=7536&m=0" },
  { name: "World Affairs Council", category: "Nonprofit & Community Organizations", website: "https://wacphila.org/join-our-team/" },
  { name: "Connect the Dots", category: "Nonprofit & Community Organizations", website: "https://connectthedots.us" },
  { name: "Ronald McDonald House", category: "Nonprofit & Community Organizations", website: "https://www.ronaldmcdonaldhousephilly.org/careers/" },
  { name: "Rivers Casino", category: "Hospitality / Food & Beverage Partners", website: "https://www.riverscasino.com/philadelphia/careers" },
  { name: "Panda Express", category: "Hospitality / Food & Beverage Partners", website: "https://www.pandacareers.com/jobs/?searchlocation=Philadelphia%2C+PA" },
  { name: "Marriott Old City", category: "Hospitality / Food & Beverage Partners", website: "https://recruiting.ultipro.com/POL1006/JobBoard/c0e3f015-388f-2bf6-e3ac-af081fcad685/" },
  { name: "Cook N Solo", category: "Hospitality / Food & Beverage Partners", website: "https://culinaryagents.com/groups/75-COOKNSOLO-Restaurants" },
  { name: "Loews Hotel", category: "Hospitality / Food & Beverage Partners", website: "https://careers.loewshotels.com/search/?keyword=Philadelphia" },
  { name: "Marshall's Distribution Center", category: "Manufacturing Partners", website: "https://jobs.tjx.com/global/en/search-results?keywords=Philadelphia" },
  { name: "La Colombe / Chobani", category: "Manufacturing Partners", website: "https://www.lacolombe.com/pages/careers" },
  { name: "Deval LifeCycle", category: "Manufacturing Partners", website: "https://recruitingbypaycor.com/career/CareerHome.action?clientId=8a7883c681b199c90181db7884ea1102" },
  { name: "Newman Paperboard", category: "Manufacturing Partners", website: "https://newmanpaperboard.com/careers" },
  { name: "Just Born", category: "Manufacturing Partners", website: "https://www.justborn.com/join-our-team" },
  { name: "ACCU Staffing", category: "Staffing & Temp Agency Partners", website: "https://www.accustaffing.com/" },
  { name: "Express Employment Professionals", category: "Staffing & Temp Agency Partners", website: "https://www.expresspros.com/us-pennsylvania-philadelphia-center-city/job-seekers/job-openings" }
];
